"""empty message

Revision ID: 30f0febaf197
Revises: 55cb0367fd69
Create Date: 2019-05-10 21:20:06.312229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f0febaf197'
down_revision = '55cb0367fd69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_constraint(u'user_profile_user_name_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['username'])
    op.drop_column('user_profile', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_user_name_key', 'user_profile', ['user_name'])
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###
