"""empty message

Revision ID: 33a80567ec21
Revises: 4372b89d8e2b
Create Date: 2019-05-09 14:49:18.031915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a80567ec21'
down_revision = '4372b89d8e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'user_name')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
