"""empty message

Revision ID: ae0ddfe503db
Revises: ca4aa1e89ad1
Create Date: 2019-05-10 19:28:12.900368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0ddfe503db'
down_revision = 'ca4aa1e89ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.drop_column('user_profile', 'lastname')
    op.drop_column('user_profile', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'last_name')
    op.drop_column('user_profile', 'first_name')
    # ### end Alembic commands ###
