"""empty message

Revision ID: ca4aa1e89ad1
Revises: a08a3c845cbe
Create Date: 2019-05-09 15:35:39.318997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4aa1e89ad1'
down_revision = 'a08a3c845cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('role', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'role')
    # ### end Alembic commands ###
