"""empty message

Revision ID: e74edf97b234
Revises: 3c7482272fcf
Create Date: 2019-05-19 22:16:14.232068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74edf97b234'
down_revision = '3c7482272fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=80), nullable=True))
    op.drop_constraint(u'users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_username_key', 'users', ['username'])
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
